language: python
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
install:
  - make requirements
script:
  - make selfcheck
  - make quality
  - make test
  - make validate_translations
notifications:
  email: false
addons:
  firefox: 36.0
